CREATE TABLE customer (
    id                        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_ref              VARCHAR(20) NOT NULL UNIQUE,
    first_name                VARCHAR(100),
    last_name                 VARCHAR(100),
    gender                    CHAR(1),
    date_of_birth             DATE,
    email                     VARCHAR(255) UNIQUE,
    phone_number              VARCHAR(20),
    city                      VARCHAR(100),
    state                     VARCHAR(100),
    country                   CHAR(2),
    postal_code               VARCHAR(20),
    occupation                VARCHAR(100),
    annual_income             NUMERIC(18, 2),
    marital_status            VARCHAR(20),
    education_level           VARCHAR(50),
    employment_status         VARCHAR(30),
    customer_since            DATE,
    customer_segment          VARCHAR(20),
    kyc_status                VARCHAR(20),
    risk_rating               VARCHAR(10),
    is_politically_exposed    BOOLEAN NOT NULL DEFAULT FALSE,
    preferred_channel         VARCHAR(50),
    email_verified            BOOLEAN NOT NULL DEFAULT FALSE,
    phone_verified            BOOLEAN NOT NULL DEFAULT FALSE,
    num_complaints_last_year  INTEGER,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);
